# Generated by Django 5.1.3 on 2025-02-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurentapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("1", "pending"), ("2", "declined"), ("3", "approved")],
                default="1",
                max_length=50,
            ),
        ),
    ]
