# Generated by Django 5.1.3 on 2025-02-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurentapp", "0002_alter_booking_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="dete_ordered",
            new_name="date_ordered",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="Transaction_id",
            new_name="transaction_id",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="dete_added",
            new_name="date_added",
        ),
    ]
